### ISSUE TITLE
Keyboard interrupt inside the interactive shell makes it unusable

### ISSUE THREAD

**Issue by albertopaltrinieri** [xyb/robotframework-debuglibrary#73] opened 2023-04-04 06:20 UTC
Similarly to old issue #26, sending a keyboard interrupt (by pushing ctrl+c) in the shell on one keyword, makes the shell unusable:

\>\>\>\>\> Enter interactive shell
Only accepted plain text format keyword separated with two or more spaces.
Type "help" for more information.
\> Sleep    30s
--> Press Ctrl+C to interrupt sleep command
[ ERROR ] Execution stopped by user.
Test error, press RETURN

Robot Framework 5.0.1 (Python 3.9.16 on linux)
DebugLibrary 2.3.0 (sha256: 2c3fb8390afc3934777657d3cf8a1674c731000035d614a21552ae96ca99fd30)

**Comment by xyb** [comment] 2024-01-11 07:49
@albertopaltrinieri I apologize for the delayed response. I have tested this on Linux and Mac and was unable to reproduce the issue. I will close this issue, but if you are still having this problem, please feel free to reopen it.

**Closed by xyb** 2024-01-11 07:49 UTC
